In [4]:
from sklearn import preprocessing
import numpy as np

In [14]:
data = np.array( [[ -1, 2, 0],
                  [ 2, -1, 2],
                  [ 1, -1, -1]])

In [6]:
data.mean( axis =0 )

array([0.66666667, 0.        , 0.33333333])

In [9]:
data = preprocessing.scale(data)

In [10]:
data.mean( axis =0)

array([1.2952602e-16, 0.0000000e+00, 0.0000000e+00])

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()

In [16]:
scaler.fit(data)
data_standard = scaler.transform(data)

In [17]:
data_standard.mean( axis = 0)

array([1.2952602e-16, 0.0000000e+00, 0.0000000e+00])