In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
from sklearn.model_selection import cross_val_predict

In [ ]:
import seaborn as sns

In [ ]:
%matplotlib inline

In [ ]:
df = sns.load_dataset('titanic')

In [ ]:
 df.shape

(891, 15)

In [ ]:
%df.dropna(inplace=True)

UsageError: Line magic function `%df.dropna(inplace=True)` not found.


In [ ]:
df.shape

(891, 15)

In [ ]:
df['sex'].unique()

array(['male', 'female'], dtype=object)

In [ ]:
df['sex'].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder


In [ ]:
le = LabelEncoder()

In [ ]:
X = df[ [ 'pclass', 'sex', 'age']].copy()

In [ ]:
X['sex'] = le.fit_transform(X['sex'])

In [ ]:
X.head()

pclass  sex   age
0       3    1  22.0
1       1    0  38.0
2       3    0  26.0
3       1    0  35.0
4       3    1  35.0

In [ ]:
X.describe()

pclass         sex         age
count  891.000000  891.000000  714.000000
mean     2.308642    0.647587   29.699118
std      0.836071    0.477990   14.526497
min      1.000000    0.000000    0.420000
25%      2.000000    0.000000   20.125000
50%      3.000000    1.000000   28.000000
75%      3.000000    1.000000   38.000000
max      3.000000    1.000000   80.000000

In [ ]:
X = df[['pclass', 'sex', 'age', 'survived']].copy()
X.dropna()
y = X['survived']
X.drop('survived', axis=1, inplace=True)


In [ ]:
y.head(), X.head()

(0    0
 1    1
 2    1
 3    1
 4    0
 Name: survived, dtype: int64,
    pclass     sex   age
 0       3    male  22.0
 1       1  female  38.0
 2       3  female  26.0
 3       1  female  35.0
 4       3    male  35.0)

In [ ]:
X

In [ ]:
X['sex'] = le.fit_transform(X['sex'])

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from sklearn.ensemble import BaggingClassifier

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report,roc_auc_score

In [ ]:
def print_score(clf, X_train, X_test, y_train, y_test, train=True):
  lb = preprocessing.LabelBinarizer()
  if train:
    y_pred = clf.predict(X_train)
    print("Train Result:\n")
    print("accuracy score: {0:.4f}\n".format(accuracy_score(y_train, y_pred)))
    print("Classification Report:\n {} \n".format(classification_report(y_train, y_pred)))
    print("Confusion Matrix:\n {} \n".format(confusion_matrix(y_train, y_pred)))
    print("ROC AUC: {0:.4f}\n".format(roc_auc_score(lb.fit_transform(y_train), lb.transform(y_pred))))
    res = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
    print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
    print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))

  elif train == False: # Corrected the syntax error here
    # ...
    # test performance
    # ...
    res_test = clf.predict(X_test)
    lb.fit(y_train) # Fit the binarizer on the training data

    print("Test Result: \n")
    print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test,
                                                          res_test)))

    print("Classification Report: \n{}\n".format(classification_report(y_test,
                                                                      res_test)))

    print("Confusion Matrix: \n{}\n".format(confusion_matrix(y_test,
                                                           res_test)))

    print("ROC AUC: {0:.4f}\n".format(roc_auc_score(lb.transform(y_test),
                                                    lb.transform(res_test))))

In [ ]:
clf1 = DecisionTreeClassifier(random_state=42)

In [ ]:
clf1.fit( X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:
print_score(clf1, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.8812

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.95      0.91       390
           1       0.90      0.77      0.83       233

    accuracy                           0.88       623
   macro avg       0.89      0.86      0.87       623
weighted avg       0.88      0.88      0.88       623
 

Confusion Matrix:
 [[370  20]
 [ 54 179]] 

ROC AUC: 0.8585

Average Accuracy: 	 0.7832
Accuracy SD: 		 0.0448


In [ ]:
print_score(clf1, X_train, X_test, y_train, y_test, train=False)

Test Result: 

accuracy score: 0.8284

Classification Report: 
              precision    recall  f1-score   support

           0       0.83      0.89      0.86       159
           1       0.82      0.74      0.78       109

    accuracy                           0.83       268
   macro avg       0.83      0.81      0.82       268
weighted avg       0.83      0.83      0.83       268


Confusion Matrix: 
[[141  18]
 [ 28  81]]

ROC AUC: 0.8150



In [ ]:
clf_bag = BaggingClassifier(estimator=clf1, n_estimators=1000, n_jobs=-1, random_state=42)

In [ ]:
clf_bag.fit( X_train, y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(random_state=42),
                  n_estimators=1000, n_jobs=-1, random_state=42)

In [ ]:
print_score(clf_bag, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.8812

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.95      0.91       390
           1       0.90      0.77      0.83       233

    accuracy                           0.88       623
   macro avg       0.89      0.86      0.87       623
weighted avg       0.88      0.88      0.88       623
 

Confusion Matrix:
 [[370  20]
 [ 54 179]] 

ROC AUC: 0.8585

Average Accuracy: 	 0.7783
Accuracy SD: 		 0.0597


In [ ]:
print_score(clf_bag, X_train, X_test, y_train, y_test, train=False)

Test Result: 

accuracy score: 0.8396

Classification Report: 
              precision    recall  f1-score   support

           0       0.85      0.88      0.87       160
           1       0.82      0.78      0.80       108

    accuracy                           0.84       268
   macro avg       0.84      0.83      0.83       268
weighted avg       0.84      0.84      0.84       268


Confusion Matrix: 
[[141  19]
 [ 24  84]]

ROC AUC: 0.8295



In [ ]:
clf_bagOOB = BaggingClassifier(estimator=clf1, n_estimators=1000, n_jobs=-1, random_state=42, oob_score = True)

In [ ]:
clf_bagOOB.fit( X_train, y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(random_state=42),
                  n_estimators=1000, n_jobs=-1, oob_score=True,
                  random_state=42)

In [ ]:
print_score(clf_bagOOB, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.8780

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.92      0.90       389
           1       0.86      0.80      0.83       234

    accuracy                           0.88       623
   macro avg       0.87      0.86      0.87       623
weighted avg       0.88      0.88      0.88       623
 

Confusion Matrix:
 [[359  30]
 [ 46 188]] 

ROC AUC: 0.8631

Average Accuracy: 	 0.7738
Accuracy SD: 		 0.0575


In [ ]:
X.shape

(891, 3)