In [87]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns



In [88]:
from sklearn.model_selection import train_test_split

In [89]:
df = sns.load_dataset('titanic')

In [90]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [91]:
X = df[['pclass','age', 'sex', 'survived']].copy()

In [92]:
X = X.dropna()

In [93]:
y = X['survived']

In [94]:
del X['survived']

In [95]:
X.head()

pclass   age     sex
0       3  22.0    male
1       1  38.0  female
2       3  26.0  female
3       1  35.0  female
4       3  35.0    male

In [121]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['sex'] =le.fit_transform(X['sex'])

In [122]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [123]:
from sklearn.ensemble import AdaBoostClassifier

In [124]:
clf_ada = AdaBoostClassifier(n_estimators=100)

In [125]:
X.head()

pclass   age  sex
0       3  22.0    1
1       1  38.0    0
2       3  26.0    0
3       1  35.0    0
4       3  35.0    1

In [126]:
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
from sklearn.model_selection import cross_val_score


In [127]:
def print_score(clf, X_train, X_test, y_train, y_test, train=True):
  lb = preprocessing.LabelBinarizer()
  if train:
    y_pred = clf.predict(X_train)
    print("Train Result:\n")
    print("accuracy score: {0:.4f}\n".format(accuracy_score(y_train, y_pred)))
    print("Classification Report:\n {} \n".format(classification_report(y_train, y_pred)))
    print("Confusion Matrix:\n {} \n".format(confusion_matrix(y_train, y_pred)))
    print("ROC AUC: {0:.4f}\n".format(roc_auc_score(lb.fit_transform(y_train), lb.transform(y_pred))))
    res = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
    print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
    print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))

  elif train == False: # Corrected the syntax error here
    # ...
    # test performance
    # ...
    res_test = clf.predict(X_test)
    lb.fit(y_train) # Fit the binarizer on the training data

    print("Test Result: \n")
    print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test,
                                                          res_test)))

    print("Classification Report: \n{}\n".format(classification_report(y_test,
                                                                      res_test)))

    print("Confusion Matrix: \n{}\n".format(confusion_matrix(y_test,
                                                           res_test)))

    print("ROC AUC: {0:.4f}\n".format(roc_auc_score(lb.transform(y_test),
                                                    lb.transform(res_test))))
    print("Average Accuracy: \t {0:.4f}".format(np.mean(res_test)))
    print("Accuracy SD: \t\t {0:.4f}".format(np.std(res_test)))

In [129]:
clf_ada.fit(X_train, y_train)

AdaBoostClassifier(n_estimators=100)

In [130]:
print_score(clf_ada, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.8196

Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.84      0.85       337
           1       0.77      0.79      0.78       234

    accuracy                           0.82       571
   macro avg       0.81      0.82      0.81       571
weighted avg       0.82      0.82      0.82       571
 

Confusion Matrix:
 [[283  54]
 [ 49 185]] 

ROC AUC: 0.8152

Average Accuracy: 	 0.8108
Accuracy SD: 		 0.0457


In [132]:
print_score(clf_ada, X_train, X_test, y_train, y_test, train=False)

Test Result: 

accuracy score: 0.7273

Classification Report: 
              precision    recall  f1-score   support

           0       0.81      0.72      0.76        87
           1       0.63      0.73      0.68        56

    accuracy                           0.73       143
   macro avg       0.72      0.73      0.72       143
weighted avg       0.74      0.73      0.73       143


Confusion Matrix: 
[[63 24]
 [15 41]]

ROC AUC: 0.7281

Average Accuracy: 	 0.4545
Accuracy SD: 		 0.4979


In [106]:
X.shape

(714, 3)

In [107]:
X_test.shape

(143, 3)

In [133]:
from sklearn.ensemble import RandomForestClassifier

In [134]:
random = RandomForestClassifier()

In [135]:
clf_ada_random = AdaBoostClassifier(random, n_estimators=100)

In [136]:
clf_ada_random.fit(X_train, y_train)

AdaBoostClassifier(estimator=RandomForestClassifier(), n_estimators=100)

In [137]:
clf_ada_random.fit(X_train, y_train)

AdaBoostClassifier(estimator=RandomForestClassifier(), n_estimators=100)

In [138]:
print_score(clf_ada_random, X_train, X_test, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9072

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.95      0.92       337
           1       0.92      0.85      0.88       234

    accuracy                           0.91       571
   macro avg       0.91      0.90      0.90       571
weighted avg       0.91      0.91      0.91       571
 

Confusion Matrix:
 [[319  18]
 [ 35 199]] 

ROC AUC: 0.8985

Average Accuracy: 	 0.8108
Accuracy SD: 		 0.0472


In [139]:
print_score(clf_ada_random, X_train, X_test, y_train, y_test, train=False)

Test Result: 

accuracy score: 0.7762

Classification Report: 
              precision    recall  f1-score   support

           0       0.81      0.83      0.82        87
           1       0.72      0.70      0.71        56

    accuracy                           0.78       143
   macro avg       0.77      0.76      0.76       143
weighted avg       0.78      0.78      0.78       143


Confusion Matrix: 
[[72 15]
 [17 39]]

ROC AUC: 0.7620

Average Accuracy: 	 0.3776
Accuracy SD: 		 0.4848
